"""empty message

Revision ID: 212d596f1c5e
Revises: 96504305e976
Create Date: 2023-08-28 18:54:04.810009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212d596f1c5e'
down_revision = '96504305e976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_name', sa.String(length=100), nullable=False),
    sa.Column('goal_amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_set', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_budget_setting', sa.Date(), nullable=True))

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_column('last_budget_setting')
        batch_op.drop_column('day_set')

    op.drop_table('financial_goal')
    # ### end Alembic commands ###
