"""added is_reccuring

Revision ID: 96504305e976
Revises: 
Create Date: 2023-08-28 00:41:54.285136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96504305e976'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recurring_frequency', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('recurring_frequency')
        batch_op.drop_column('is_recurring')

    # ### end Alembic commands ###
