"""updated user and budget modesl

Revision ID: ab5276a5fc07
Revises: 
Create Date: 2023-08-20 16:48:46.970508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab5276a5fc07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('unique_budgettype_per_user', type_='unique')
        batch_op.create_unique_constraint('unique_category_per_user', ['user_id', 'category'])
        batch_op.drop_column('budget_type')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_budget', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('main_budget')

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_type', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint('unique_category_per_user', type_='unique')
        batch_op.create_unique_constraint('unique_budgettype_per_user', ['user_id', 'budget_type'])
        batch_op.drop_column('category')

    # ### end Alembic commands ###
