"""Made budget_amount nullable

Revision ID: efb914a22fc0
Revises: ab5276a5fc07
Create Date: 2023-08-23 16:57:45.262840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb914a22fc0'
down_revision = 'ab5276a5fc07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.alter_column('budget_amount',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.alter_column('budget_amount',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
